const localQuotes = {
  quotes: [
    {
      _id: "Nz3BafiyALJ",
      content:
        "Pain and foolishness lead to great bliss and complete knowledge, for Eternal Wisdom created nothing under the sun in vain.",
      author: "Kahlil Gibran",
      tags: ["Wisdom"],
      authorSlug: "kahlil-gibran",
      length: 122,
      dateAdded: "2019-09-13",
      dateModified: "2023-04-14",
    },
    {
      _id: "7Gy2Y5Zxuzh",
      content: "Autumn is a second spring when every leaf is a flower.",
      author: "Albert Camus",
      tags: ["Famous Quotes", "Nature"],
      authorSlug: "albert-camus",
      length: 54,
      dateAdded: "2019-12-13",
      dateModified: "2023-04-14",
    },
    {
      _id: "RrdntXFj8cLK",
      content: "Memory is the mother of all wisdom.",
      author: "Samuel Johnson",
      tags: ["Famous Quotes", "Wisdom"],
      authorSlug: "samuel-johnson",
      length: 35,
      dateAdded: "2019-02-17",
      dateModified: "2023-04-14",
    },
    {
      _id: "BesY5YKGp5W0",
      content:
        "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.",
      author: "Anatole France",
      tags: ["Famous Quotes", "Inspirational"],
      authorSlug: "anatole-france",
      length: 98,
      dateAdded: "2019-08-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "4uAgduNKEAKW",
      content: "For everything that lives is holy, life delights in life.",
      author: "William Blake",
      tags: ["Famous Quotes"],
      authorSlug: "william-blake",
      length: 57,
      dateAdded: "2020-05-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "mT4iARsFw",
      content: "Always keep an open mind and a compassionate heart.",
      author: "Phil Jackson",
      tags: ["Wisdom"],
      authorSlug: "phil-jackson",
      length: 51,
      dateAdded: "2019-08-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "DcSFCGK7rYov",
      content:
        "If the single man plant himself indomitably on his instincts, and there abide, the huge world will come round to him.",
      author: "Ralph Waldo Emerson",
      tags: ["Famous Quotes"],
      authorSlug: "ralph-waldo-emerson",
      length: 117,
      dateAdded: "2020-01-15",
      dateModified: "2023-04-14",
    },
    /*{
      _id: "py0SqUMHGW9",
      author: "Howard H. Aiken",
      content:
        "Don't worry about people stealing your ideas. If your ideas are any good, you'll have to ram them down people's throats.",
      tags: ["Business"],
      authorSlug: "howard-h-aiken",
      length: 120,
      dateAdded: "2022-07-06",
      dateModified: "2023-04-14",
    },*/
    {
      _id: "97Zb1PjxN7",
      content:
        "A true friend is someone who is there for you when he'd rather be anywhere else.",
      author: "Len Wein",
      tags: ["Friendship"],
      authorSlug: "len-wein",
      length: 80,
      dateAdded: "2019-12-02",
      dateModified: "2023-04-14",
    },
    {
      _id: "UydvuUuGWjGo",
      content: "We read the world wrong and say that it deceives us.",
      author: "Rabindranath Tagore",
      tags: ["Famous Quotes"],
      authorSlug: "rabindranath-tagore",
      length: 52,
      dateAdded: "2020-04-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "1n4fgICLEB_g",
      content: "Action is the foundational key to all success.",
      author: "Pablo Picasso",
      tags: ["Success"],
      authorSlug: "pablo-picasso",
      length: 46,
      dateAdded: "2020-02-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "LQt8A2sDPrZz",
      content:
        "Through perseverance many people win success out of what seemed destined to be certain failure.",
      author: "Benjamin Disraeli",
      tags: ["Success"],
      authorSlug: "benjamin-disraeli",
      length: 95,
      dateAdded: "2020-01-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "sF8AwOka_A",
      content:
        "Our most intimate friend is not he to whom we show the worst, but the best of our nature.",
      author: "Nathaniel Hawthorne",
      tags: ["Friendship"],
      authorSlug: "nathaniel-hawthorne",
      length: 89,
      dateAdded: "2019-03-24",
      dateModified: "2023-04-14",
    },
    {
      _id: "JvN_exUiTvKU",
      content:
        "Ability is what you're capable of doing. Motivation determines what you do. Attitude determines how well you do it.",
      author: "Lou Holtz",
      tags: ["Famous Quotes", "Inspirational"],
      authorSlug: "lou-holtz",
      length: 115,
      dateAdded: "2019-01-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "Um2MLxmE-Dv-",
      content:
        "A fine quotation is a diamond on the finger of a man of wit, and a pebble in the hand of a fool.",
      author: "Joseph Roux",
      tags: ["Famous Quotes"],
      authorSlug: "joseph-roux",
      length: 96,
      dateAdded: "2020-09-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "BqFJ5FP6LdA",
      content: "Write your plans in pencil and give God the eraser.",
      author: "Paulo Coelho",
      tags: ["Famous Quotes"],
      authorSlug: "paulo-coelho",
      length: 51,
      dateAdded: "2019-08-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "sBETVwDHY0",
      content:
        "It has long been an axiom of mine that the little things are infinitely the most important.",
      author: "Arthur Conan Doyle",
      tags: ["Wisdom"],
      authorSlug: "arthur-conan-doyle",
      length: 91,
      dateAdded: "2021-04-23",
      dateModified: "2023-04-14",
    },
    /*{
      _id: "Z1z6kZ2Qp8",
      author: "Elon Musk",
      content:
        "If you're trying to create a company, it's like baking a cake. You have to have all the ingredients in the right proportion.",
      tags: ["Business"],
      authorSlug: "elon-musk",
      length: 124,
      dateAdded: "2022-07-06",
      dateModified: "2023-04-14",
    },*/
    {
      _id: "ML3d7eMwRfr3",
      content: "There is nothing impossible to him who will try.",
      author: "Alexander the Great",
      tags: ["Famous Quotes", "Inspirational"],
      authorSlug: "alexander-the-great",
      length: 48,
      dateAdded: "2020-12-17",
      dateModified: "2023-04-14",
    },
    {
      _id: "KJhB_lkgrbPa",
      content:
        "It is better to understand a little than to misunderstand a lot.",
      author: "Anatole France",
      tags: ["Famous Quotes"],
      authorSlug: "anatole-france",
      length: 64,
      dateAdded: "2020-02-22",
      dateModified: "2023-04-14",
    },
    {
      _id: "VNbPhxpsCQrO",
      content:
        "Remember always that you not only have the right to be an individual, you have an obligation to be one.",
      author: "Eleanor Roosevelt",
      tags: ["Famous Quotes"],
      authorSlug: "eleanor-roosevelt",
      length: 103,
      dateAdded: "2021-03-28",
      dateModified: "2023-04-14",
    },
    {
      _id: "_DRD2nPtR3",
      content:
        "Spectacular achievement is always preceded by unspectacular preparation.",
      author: "Robert Schuller",
      tags: ["Wisdom"],
      authorSlug: "robert-schuller",
      length: 72,
      dateAdded: "2020-03-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "PTVGpNzPj2ip",
      content:
        "I'm not in this world to live up to your expectations and you're not in this world to live up to mine.",
      author: "Bruce Lee",
      tags: ["Famous Quotes"],
      authorSlug: "bruce-lee",
      length: 102,
      dateAdded: "2021-04-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "UZRrCYy2WC0n",
      content:
        "Never apologize for showing feelings. When you do so, you apologize for the truth.",
      author: "Benjamin Disraeli",
      tags: ["Famous Quotes"],
      authorSlug: "benjamin-disraeli",
      length: 82,
      dateAdded: "2020-01-31",
      dateModified: "2023-04-14",
    },
    {
      _id: "xEYjoxqQhRfC",
      content: "A man is great by deeds, not by birth.",
      author: "Chanakya",
      tags: ["Famous Quotes"],
      authorSlug: "chanakya",
      length: 38,
      dateAdded: "2020-09-29",
      dateModified: "2023-04-14",
    },
    {
      _id: "NzmVr08q5EkO",
      content:
        "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
      author: "Benjamin Franklin",
      tags: ["Famous Quotes"],
      authorSlug: "benjamin-franklin",
      length: 70,
      dateAdded: "2020-04-02",
      dateModified: "2023-04-14",
    },
    {
      _id: "f1aZRYvKb7Ga",
      content:
        "You have to do your own growing no matter how tall your grandfather was.",
      author: "Abraham Lincoln",
      tags: ["Famous Quotes", "Life", "Wisdom"],
      authorSlug: "abraham-lincoln",
      length: 72,
      dateAdded: "2019-08-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "8Lkh3gqcSh",
      content: "Difficulties increase the nearer we get to the goal.",
      author: "Johann Wolfgang von Goethe",
      tags: ["Famous Quotes", "Inspirational"],
      authorSlug: "johann-wolfgang-von-goethe",
      length: 52,
      dateAdded: "2021-01-19",
      dateModified: "2023-04-14",
    },
    {
      _id: "Hpo_qh-q76A",
      author: "Reggie Jackson (basketball, born 1990)",
      content: "Fans don't boo nobodies.",
      tags: ["Sports", "Competition"],
      authorSlug: "reggie-jackson-basketball-born-1990",
      length: 24,
      dateAdded: "2022-07-06",
      dateModified: "2023-04-14",
    },
    {
      _id: "Dg-s-e2zAXKs",
      content:
        "One who gains strength by overcoming obstacles possesses the only strength which can overcome adversity.",
      author: "Albert Schweitzer",
      tags: ["Famous Quotes", "Inspirational"],
      authorSlug: "albert-schweitzer",
      length: 104,
      dateAdded: "2019-11-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "Dy894N3FJzj8",
      content:
        "I prefer to be true to myself, even at the hazard of incurring the ridicule of others, rather than to be false, and to incur my own abhorrence.",
      author: "Frederick Douglass",
      tags: ["Famous Quotes"],
      authorSlug: "frederick-douglass",
      length: 143,
      dateAdded: "2021-01-10",
      dateModified: "2023-04-14",
    },
    {
      _id: "3Jk60HlbZFu9",
      content:
        "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.",
      author: "Harriet Tubman",
      tags: ["Famous Quotes", "Success", "Inspirational"],
      authorSlug: "harriet-tubman",
      length: 165,
      dateAdded: "2021-05-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "kKAMmRhnyps",
      content:
        "All the great performers I have worked with are fueled by a personal dream.",
      author: "John Eliot",
      tags: ["Success"],
      authorSlug: "john-eliot",
      length: 75,
      dateAdded: "2019-02-13",
      dateModified: "2023-04-14",
    },
    {
      _id: "BYFMDg3gOH",
      content:
        "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.",
      author: "Audrey Hepburn",
      tags: ["Wisdom"],
      authorSlug: "audrey-hepburn",
      length: 163,
      dateAdded: "2020-10-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "S1jK2eB0lfyM",
      content:
        "Just as a flower, which seems beautiful has color but no perfume, so are the fruitless words of a man who speaks them but does them not.",
      author: "Dhammapada",
      tags: ["Famous Quotes"],
      authorSlug: "dhammapada",
      length: 136,
      dateAdded: "2019-12-23",
      dateModified: "2023-04-14",
    },
    /*{
      _id: "Aooogq1lu-",
      author: "Theodore Isaac Rubin",
      content:
        "Happiness does not come from doing easy work but from the afterglow of satisfaction that comes after the achievement of a difficult task that demanded our best.",
      tags: ["Business"],
      authorSlug: "theodore-isaac-rubin",
      length: 160,
      dateAdded: "2022-07-06",
      dateModified: "2023-04-14",
    },*/
    {
      _id: "6YlJjSaAbKdA",
      content:
        "Our kindness may be the most persuasive argument for that which we believe.",
      author: "Gordon Hinckley",
      tags: ["Famous Quotes"],
      authorSlug: "gordon-hinckley",
      length: 75,
      dateAdded: "2019-08-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "51SwnjMnK0Qy",
      content:
        "A successful person is one who can lay a firm foundation with the bricks that others throw at him or her.",
      author: "David Brinkley",
      tags: ["Success"],
      authorSlug: "david-brinkley",
      length: 105,
      dateAdded: "2019-02-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "PDMZifPN52pg",
      content:
        "If you spend your whole life waiting for the storm, you'll never enjoy the sunshine.",
      author: "Morris West",
      tags: ["Famous Quotes"],
      authorSlug: "morris-west",
      length: 84,
      dateAdded: "2021-03-26",
      dateModified: "2023-04-14",
    },
    {
      _id: "ZIUHncH2frxc",
      content:
        "The winner ain't the one with the fastest car it's the one who refuses to lose.",
      author: "Dale Earnhardt",
      tags: ["Famous Quotes"],
      authorSlug: "dale-earnhardt",
      length: 79,
      dateAdded: "2021-01-10",
      dateModified: "2023-04-14",
    },
    {
      _id: "PHkGb4ppfvTb",
      content:
        "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
      author: "Leonardo da Vinci",
      tags: ["Famous Quotes"],
      authorSlug: "leonardo-da-vinci",
      length: 153,
      dateAdded: "2021-05-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "za_rrJe3SE",
      content:
        "The essence of true friendship is to make allowance for another's little lapses.",
      author: "Ovid",
      tags: ["Friendship"],
      authorSlug: "ovid",
      length: 80,
      dateAdded: "2020-02-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "9_Jco348Lkgw",
      content:
        "The greater part of human pain is unnecessary. It is self-created as long as the unobserved mind runs your life.",
      author: "Eckhart Tolle",
      tags: ["Famous Quotes"],
      authorSlug: "eckhart-tolle",
      length: 112,
      dateAdded: "2020-02-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "d76RCKoNh69P",
      content: "Be your own hero, it's cheaper than a movie ticket.",
      author: "Doug Horton",
      tags: ["Famous Quotes"],
      authorSlug: "doug-horton",
      length: 51,
      dateAdded: "2019-02-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "2hNPcjVsMTb",
      content: "Every problem has a gift for you in its hands.",
      author: "Richard Bach",
      tags: ["Famous Quotes"],
      authorSlug: "richard-bach",
      length: 46,
      dateAdded: "2020-01-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "d-htbqN3YT",
      content:
        "It may happen sometimes that a long debate becomes the cause of a longer friendship. Commonly, those who dispute with one another at last agree.",
      author: "Elbert Hubbard",
      tags: ["Friendship"],
      authorSlug: "elbert-hubbard",
      length: 144,
      dateAdded: "2019-08-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "OP57ZqfTQf",
      content:
        "We are what our thoughts have made us; so take care about what you think. Words are secondary. Thoughts live; they travel far.",
      author: "Swami Vivekananda",
      tags: ["Wisdom"],
      authorSlug: "swami-vivekananda",
      length: 126,
      dateAdded: "2019-10-18",
      dateModified: "2023-04-14",
    },
    {
      _id: "DBkTDkczWkg",
      content: "You can't shake hands with a clenched fist.",
      author: "Indira Gandhi",
      tags: ["Wisdom"],
      authorSlug: "indira-gandhi",
      length: 43,
      dateAdded: "2019-02-11",
      dateModified: "2023-04-14",
    },
    {
      _id: "OG9-EbvEi-v",
      content: "We must become the change we want to see.",
      author: "Mahatma Gandhi",
      tags: ["Change", "Wisdom"],
      authorSlug: "mahatma-gandhi",
      length: 41,
      dateAdded: "2019-10-18",
      dateModified: "2023-04-14",
    },
    {
      _id: "ukNRwb5z5mVj",
      content:
        "When you discover your mission, you will feel its demand. It will fill you with enthusiasm and a burning desire to get to work on it.",
      author: "W. Clement Stone",
      tags: ["Famous Quotes"],
      authorSlug: "w-clement-stone",
      length: 133,
      dateAdded: "2019-03-24",
      dateModified: "2023-04-14",
    },
    {
      _id: "ULj6Dce6aMta",
      content:
        "The more light you allow within you, the brighter the world you live in will be.",
      author: "Shakti Gawain",
      tags: ["Famous Quotes"],
      authorSlug: "shakti-gawain",
      length: 80,
      dateAdded: "2019-06-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "97Zb1PjxN7",
      content:
        "A true friend is someone who is there for you when he'd rather be anywhere else.",
      author: "Len Wein",
      tags: ["Friendship"],
      authorSlug: "len-wein",
      length: 80,
      dateAdded: "2019-12-02",
      dateModified: "2023-04-14",
    },
    {
      _id: "S_61PHNDnbZ",
      content: "Wisdom is the supreme part of happiness.",
      author: "Sophocles",
      tags: ["Famous Quotes", "Wisdom"],
      authorSlug: "sophocles",
      length: 40,
      dateAdded: "2020-04-02",
      dateModified: "2023-04-14",
    },
    {
      _id: "uahnKaDQw2Lw",
      content:
        "Three things in human life are important. The first is to be kind. The second is to be kind. The third is to be kind.",
      author: "Henry James",
      tags: ["Famous Quotes"],
      authorSlug: "henry-james",
      length: 117,
      dateAdded: "2019-02-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "8ry084PzfT",
      content:
        "A true friend freely, advises justly, assists readily, adventures boldly, takes all patiently, defends courageously, and continues a friend unchangeably.",
      author: "William C. Menninger",
      tags: ["Friendship"],
      authorSlug: "william-c-menninger",
      length: 153,
      dateAdded: "2021-02-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "HQNnn2x2Vc",
      content:
        "A passion for politics stems usually from an insatiable need, either for power, or for friendship and adulation, or a combination of both.",
      author: "Fawn M. Brodie",
      tags: ["Friendship", "Politics"],
      authorSlug: "fawn-m-brodie",
      length: 138,
      dateAdded: "2019-10-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "07yZzr0bxo",
      content:
        "Never make friends with people who are above or below you in status. Such friendships will never give you any happiness.",
      author: "Chanakya",
      tags: ["Friendship"],
      authorSlug: "chanakya",
      length: 120,
      dateAdded: "2019-02-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "8SnLHyn1oiCH",
      content:
        "Until you make peace with who you are, you will never be content with what you have.",
      author: "Doris Mortman",
      tags: ["Famous Quotes"],
      authorSlug: "doris-mortman",
      length: 84,
      dateAdded: "2019-08-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "6CE5ld-3Po",
      content:
        "We're born alone, we live alone, we die alone. Only through our love and friendship can we create the illusion for the moment that we're not alone.",
      author: "Orson Welles",
      tags: ["Friendship"],
      authorSlug: "orson-welles",
      length: 147,
      dateAdded: "2020-02-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "RTYhCs5Ka",
      author: "Charles Dickens",
      content:
        "I do not know the American gentleman, god forgive me for putting two such words together.",
      tags: ["Humorous"],
      authorSlug: "charles-dickens",
      length: 89,
      dateAdded: "2023-04-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "DlQmGRzNGo3i",
      content: "It is not in the stars to hold our destiny but in ourselves.",
      author: "William Shakespeare",
      tags: ["Famous Quotes"],
      authorSlug: "william-shakespeare",
      length: 60,
      dateAdded: "2019-08-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "e66v9zV4YFY",
      content:
        "Wise kings generally have wise counselors; and he must be a wise man himself who is capable of distinguishing one.",
      author: "Diogenes",
      tags: ["Wisdom"],
      authorSlug: "diogenes",
      length: 114,
      dateAdded: "2019-07-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "4zzDULN1Lx",
      author: "Woody Allen",
      content:
        "I took a speed-reading course and read 'War and Peace' in twenty minutes. It involves Russia.",
      tags: ["Film"],
      authorSlug: "woody-allen",
      length: 93,
      dateAdded: "2019-10-18",
      dateModified: "2023-04-14",
    },
    {
      _id: "nyqZk3TwZb_C",
      content:
        "Let us revere, let us worship, but erect and open-eyed, the highest, not the lowest; the future, not the past!",
      author: "Charlotte Perkins Gilman",
      tags: ["Wisdom"],
      authorSlug: "charlotte-perkins-gilman",
      length: 110,
      dateAdded: "2019-11-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "pnmUUNjfmcx",
      content: "Minds are like parachutes. They only function when open.",
      author: "Thomas Dewar",
      tags: ["Famous Quotes"],
      authorSlug: "thomas-dewar",
      length: 56,
      dateAdded: "2019-02-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "lLNouGqzgu",
      content:
        "Be true to yourself, help others, make each day your masterpiece, make friendship a fine art, drink deeply from good books - especially the Bible, build a shelter against a rainy day, give thanks for your blessings and pray for guidance every day.",
      author: "John Wooden",
      tags: ["Friendship"],
      authorSlug: "john-wooden",
      length: 247,
      dateAdded: "2019-02-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "T6AMWsNRE5",
      content: "Any sufficiently advanced technology is equivalent to magic.",
      author: "Arthur C. Clarke",
      tags: ["Technology"],
      authorSlug: "arthur-c-clarke",
      length: 60,
      dateAdded: "2020-01-26",
      dateModified: "2023-04-14",
    },
    {
      _id: "106v1WSTJV",
      content:
        "Science investigates; religion interprets. Science gives man knowledge which is power; religion gives man wisdom which is control.",
      author: "Martin Luther King Jr.",
      tags: ["Wisdom"],
      authorSlug: "martin-luther-king-jr",
      length: 130,
      dateAdded: "2019-02-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "4P-rQAyVux",
      content: "Never find fault with the absent.",
      author: "Alexander Pope",
      tags: ["Wisdom"],
      authorSlug: "alexander-pope",
      length: 33,
      dateAdded: "2019-06-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "tShZNRagRX",
      content:
        "This is why I loved technology: if you used it right, it could give you power and privacy.",
      author: "Cory Doctorow",
      tags: ["Technology"],
      authorSlug: "cory-doctorow",
      length: 90,
      dateAdded: "2020-12-06",
      dateModified: "2023-04-14",
    },
    {
      _id: "7Gy2Y5Zxuzh",
      content: "Autumn is a second spring when every leaf is a flower.",
      author: "Albert Camus",
      tags: ["Famous Quotes", "Nature"],
      authorSlug: "albert-camus",
      length: 54,
      dateAdded: "2019-12-13",
      dateModified: "2023-04-14",
    },
    {
      _id: "W0OwmMfXLe",
      content:
        "It is important to our friends to believe that we are unreservedly frank with them, and important to friendship that we are not.",
      author: "Mignon McLaughlin",
      tags: ["Friendship"],
      authorSlug: "mignon-mc-laughlin",
      length: 128,
      dateAdded: "2020-04-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "vpKhzzrropUL",
      content: "All great achievements require time.",
      author: "Maya Angelou",
      tags: ["Famous Quotes"],
      authorSlug: "maya-angelou",
      length: 36,
      dateAdded: "2020-05-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "U3JBbXpUnIoF",
      content:
        "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.",
      author: "The Buddha",
      tags: ["Wisdom"],
      authorSlug: "the-buddha",
      length: 117,
      dateAdded: "2021-05-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "1RmEkIqT9Cyn",
      content: "Nothing is at last sacred but the integrity of your own mind.",
      author: "Ralph Waldo Emerson",
      tags: ["Famous Quotes"],
      authorSlug: "ralph-waldo-emerson",
      length: 61,
      dateAdded: "2019-08-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "jbHSeSpkyL5H",
      content:
        "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.",
      author: "Franklin D. Roosevelt",
      tags: ["Famous Quotes"],
      authorSlug: "franklin-d-roosevelt",
      length: 118,
      dateAdded: "2021-04-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "5V7Gw25dIjvc",
      content:
        "Happiness is not something ready-made. It comes from your own actions.",
      author: "Dalai Lama",
      tags: ["Famous Quotes"],
      authorSlug: "dalai-lama",
      length: 70,
      dateAdded: "2019-08-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "e1n5aMOunl1g",
      content: "If I know what love is, it is because of you.",
      author: "Hermann Hesse",
      tags: ["Famous Quotes"],
      authorSlug: "hermann-hesse",
      length: 45,
      dateAdded: "2020-01-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "5_6lVDMuo9IM",
      content: "Happiness can exist only in acceptance.",
      author: "George Orwell",
      tags: ["Famous Quotes"],
      authorSlug: "george-orwell",
      length: 39,
      dateAdded: "2021-01-11",
      dateModified: "2023-04-14",
    },
    {
      _id: "UGTlczrORBij",
      content:
        "Nobody made a greater mistake than he who did nothing because he could do only a little.",
      author: "Edmund Burke",
      tags: ["Famous Quotes"],
      authorSlug: "edmund-burke",
      length: 88,
      dateAdded: "2019-02-17",
      dateModified: "2023-04-14",
    },
    {
      _id: "BIBarxYM26Ux",
      content: "We can do no great things, only small things with great love.",
      author: "Mother Teresa",
      tags: ["Famous Quotes"],
      authorSlug: "mother-teresa",
      length: 61,
      dateAdded: "2021-02-12",
      dateModified: "2023-04-14",
    },
    {
      _id: "mV8MJw0rVTDP",
      content:
        "I would maintain that thanks are the highest form of thought, and that gratitude is happiness doubled by wonder.",
      author: "G. K. Chesterton",
      tags: ["Famous Quotes"],
      authorSlug: "g-k-chesterton",
      length: 112,
      dateAdded: "2021-03-26",
      dateModified: "2023-04-14",
    },
    {
      _id: "S7VBLnPG-q",
      content:
        "Does wisdom perhaps appear on the earth as a raven which is inspired by the smell of carrion?",
      author: "Friedrich Nietzsche",
      tags: ["Wisdom"],
      authorSlug: "friedrich-nietzsche",
      length: 93,
      dateAdded: "2019-12-02",
      dateModified: "2023-04-14",
    },
    {
      _id: "S4oebhrV-pQ",
      content: "Fortune favors the brave.",
      author: "Virgil",
      tags: ["Famous Quotes"],
      authorSlug: "virgil",
      length: 25,
      dateAdded: "2019-06-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "2Mx1de_dko_",
      content: "Mountains cannot be surmounted except by winding paths.",
      author: "Johann Wolfgang von Goethe",
      tags: ["Famous Quotes", "Inspirational"],
      authorSlug: "johann-wolfgang-von-goethe",
      length: 55,
      dateAdded: "2020-05-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "ZXusunQQWJwQ",
      content:
        "It's not what happens to you, but how you react to it that matters.",
      author: "Epictetus",
      tags: ["Famous Quotes", "Wisdom"],
      authorSlug: "epictetus",
      length: 67,
      dateAdded: "2020-03-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "B8_nsfJfMx",
      content:
        "Laughter is not at all a bad beginning for a friendship, and it is far the best ending for one.",
      author: "Oscar Wilde",
      tags: ["Friendship"],
      authorSlug: "oscar-wilde",
      length: 95,
      dateAdded: "2020-11-10",
      dateModified: "2023-04-14",
    },
    {
      _id: "Hv_qMJFVRTO",
      content: "A good decision is based on knowledge and not on numbers.",
      author: "Plato",
      tags: ["Famous Quotes"],
      authorSlug: "plato",
      length: 57,
      dateAdded: "2020-09-09",
      dateModified: "2023-04-14",
    },
    {
      _id: "9TcfpSrTNTkv",
      content:
        "The world cares very little about what a man or woman knows; it is what a man or woman is able to do that counts.",
      author: "Booker T. Washington",
      tags: ["Famous Quotes"],
      authorSlug: "booker-t-washington",
      length: 113,
      dateAdded: "2021-03-28",
      dateModified: "2023-04-14",
    },
    {
      _id: "s-FViy5Lm3E0",
      content:
        "Do not waste yourself in rejection, nor bark against the bad, but chant the beauty of the good.",
      author: "Ralph Waldo Emerson",
      tags: ["Famous Quotes"],
      authorSlug: "ralph-waldo-emerson",
      length: 95,
      dateAdded: "2019-09-13",
      dateModified: "2023-04-14",
    },
    {
      _id: "FO4v4ZdByU",
      content:
        "A man cannot be said to succeed in this life who does not satisfy one friend.",
      author: "Henry David Thoreau",
      tags: ["Friendship"],
      authorSlug: "henry-david-thoreau",
      length: 77,
      dateAdded: "2021-01-19",
      dateModified: "2023-04-14",
    },
    {
      _id: "nRe-W6vOUe6S",
      content:
        "There is only one success: to be able to spend your life in your own way.",
      author: "Christopher Morley",
      tags: ["Success"],
      authorSlug: "christopher-morley",
      length: 73,
      dateAdded: "2019-04-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "N6l6bDDcBP",
      content: "Friendship multiplies the good of life and divides the evil.",
      author: "Baltasar Gracián",
      tags: ["Friendship"],
      authorSlug: "baltasar-gracian",
      length: 60,
      dateAdded: "2020-11-10",
      dateModified: "2023-04-14",
    },
    {
      _id: "_tnh-9akIJ0N",
      content:
        "The biggest adventure you can ever take is to live the life of your dreams.",
      author: "Oprah Winfrey",
      tags: ["Famous Quotes"],
      authorSlug: "oprah-winfrey",
      length: 75,
      dateAdded: "2019-09-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "Xof9SNxItD8Y",
      content:
        "Before you can inspire with emotion, you must be swamped with it yourself. Before you can move their tears, your own must flow. To convince them, you must yourself believe.",
      author: "Winston Churchill",
      tags: ["Famous Quotes"],
      authorSlug: "winston-churchill",
      length: 172,
      dateAdded: "2020-11-10",
      dateModified: "2023-04-14",
    },
    {
      _id: "PHkGb4ppfvTb",
      content:
        "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
      author: "Leonardo da Vinci",
      tags: ["Famous Quotes"],
      authorSlug: "leonardo-da-vinci",
      length: 153,
      dateAdded: "2021-05-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "E9rnk2e0az",
      content: "It always seems impossible until it's done.",
      author: "Nelson Mandela",
      tags: ["Inspirational"],
      authorSlug: "nelson-mandela",
      length: 43,
      dateAdded: "2021-03-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "WMAsdt9ag7fx",
      content:
        "Gratitude is not only the greatest of virtues, but the parent of all the others.",
      author: "Cicero",
      tags: ["Famous Quotes"],
      authorSlug: "cicero",
      length: 80,
      dateAdded: "2021-03-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "QIgGGw79Wb",
      content:
        "Walking with a friend in the dark is better than walking alone in the light.",
      author: "Helen Keller",
      tags: ["Friendship"],
      authorSlug: "helen-keller",
      length: 76,
      dateAdded: "2020-06-24",
      dateModified: "2023-04-14",
    },
    {
      _id: "GPwpUR7iz-",
      content:
        "If you were to offer a thirsty man all wisdom, you would not please him more than if you gave him a drink.",
      author: "Sophocles",
      tags: ["Wisdom"],
      authorSlug: "sophocles",
      length: 106,
      dateAdded: "2019-02-13",
      dateModified: "2023-04-14",
    },
    {
      _id: "ZXusunQQWJwQ",
      content:
        "It's not what happens to you, but how you react to it that matters.",
      author: "Epictetus",
      tags: ["Famous Quotes", "Wisdom"],
      authorSlug: "epictetus",
      length: 67,
      dateAdded: "2020-03-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "nm0-EMpYdg",
      content:
        "Never explain - your friends do not need it and your enemies will not believe you anyway.",
      author: "Elbert Hubbard",
      tags: ["Friendship"],
      authorSlug: "elbert-hubbard",
      length: 89,
      dateAdded: "2021-05-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "qnZp8X0a7ju1",
      content: "Miracles come in moments. Be ready and willing.",
      author: "Wayne Dyer",
      tags: ["Famous Quotes"],
      authorSlug: "wayne-dyer",
      length: 47,
      dateAdded: "2019-12-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "c2crwHSzalPu",
      content:
        "Difficulties are meant to rouse, not discourage. The human spirit is to grow strong by conflict.",
      author: "William Ellery Channing",
      tags: ["Famous Quotes", "Inspirational", "Power Quotes"],
      authorSlug: "william-ellery-channing",
      length: 96,
      dateAdded: "2020-06-24",
      dateModified: "2023-04-14",
    },
    {
      _id: "MgUl-kKgCq6",
      content: "Each day provides its own gifts.",
      author: "Marcus Aurelius",
      tags: ["Famous Quotes", "Wisdom"],
      authorSlug: "marcus-aurelius",
      length: 32,
      dateAdded: "2019-01-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "UcAqxDLZOT_M",
      content:
        "If one way be better than another, that you may be sure is nature's way.",
      author: "Aristotle",
      tags: ["Famous Quotes"],
      authorSlug: "aristotle",
      length: 72,
      dateAdded: "2019-07-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "HBLejCmmWoIy",
      content:
        "Happiness mainly comes from our own attitude, rather than from external factors.",
      author: "Dalai Lama",
      tags: ["Famous Quotes"],
      authorSlug: "dalai-lama",
      length: 80,
      dateAdded: "2020-04-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "qle6kfkGUI",
      author: "Woody Allen",
      content:
        "How is it possible to find meaning in a finite world, given my waist and shirt size?",
      tags: ["Film"],
      authorSlug: "woody-allen",
      length: 84,
      dateAdded: "2020-03-11",
      dateModified: "2023-04-14",
    },
    {
      _id: "hL3bSnfjWhS-",
      content:
        "Sometimes it is better to lose and do the right thing than to win and do the wrong thing.",
      author: "Tony Blair",
      tags: ["Famous Quotes"],
      authorSlug: "tony-blair",
      length: 89,
      dateAdded: "2021-04-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "o3B6zEa-5H",
      content: "Adopt the pace of nature: her secret is patience.",
      author: "Ralph Waldo Emerson",
      tags: ["Wisdom"],
      authorSlug: "ralph-waldo-emerson",
      length: 49,
      dateAdded: "2019-02-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "io0NDLSyHH4Q",
      content:
        "The truth you believe and cling to makes you unavailable to hear anything new.",
      author: "Pema Chödrön",
      tags: ["Famous Quotes"],
      authorSlug: "pema-chodron",
      length: 78,
      dateAdded: "2020-09-09",
      dateModified: "2023-04-14",
    },
    {
      _id: "2tKyChNM7PeF",
      content:
        "The only person who never makes mistakes is the person who never does anything.",
      author: "Denis Waitley",
      tags: ["Famous Quotes"],
      authorSlug: "denis-waitley",
      length: 79,
      dateAdded: "2020-03-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "1OXn8__F7P",
      content: "Cleverness is not wisdom.",
      author: "Euripides",
      tags: ["Wisdom"],
      authorSlug: "euripides",
      length: 25,
      dateAdded: "2019-04-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "_Ai5yulUS-s0",
      content:
        "People are not lazy. They simply have impotent goals - that is, goals that do not inspire them.",
      author: "Tony Robbins",
      tags: ["Famous Quotes"],
      authorSlug: "tony-robbins",
      length: 95,
      dateAdded: "2020-02-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "XQKtTxtLnshu",
      content:
        "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.",
      author: "Barack Obama",
      tags: ["Change", "Wisdom"],
      authorSlug: "barack-obama",
      length: 145,
      dateAdded: "2021-03-28",
      dateModified: "2023-04-14",
    },
    {
      _id: "Fk_kOv_a_9r",
      content: "What worries you masters you.",
      author: "Haddon Robinson",
      tags: ["Famous Quotes"],
      authorSlug: "haddon-robinson",
      length: 29,
      dateAdded: "2021-05-05",
      dateModified: "2023-04-14",
    },
    {
      _id: "CPlCKbTp31o",
      content: "Sadness flies away on the wings of time.",
      author: "Jean de La Fontaine",
      tags: ["Famous Quotes"],
      authorSlug: "jean-de-la-fontaine",
      length: 40,
      dateAdded: "2019-03-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "StQwgV2uHKio",
      content: "In seed time learn, in harvest teach, in winter enjoy.",
      author: "William Blake",
      tags: ["Famous Quotes"],
      authorSlug: "william-blake",
      length: 54,
      dateAdded: "2021-01-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "L63tZjtmyQX6",
      content:
        "I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.",
      author: "Marilyn Monroe",
      tags: ["Famous Quotes"],
      authorSlug: "marilyn-monroe",
      length: 202,
      dateAdded: "2021-04-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "iCcQwfTUU3",
      author: "Albert Einstein",
      content:
        "Laws alone can not secure freedom of expression; in order that every man present his views without penalty there must be spirit of tolerance in the entire population.",
      tags: ["Freedom", "Tolerance"],
      authorSlug: "albert-einstein",
      length: 166,
      dateAdded: "2023-04-06",
      dateModified: "2023-04-14",
    },
    {
      _id: "u0V3eW7NMp5T",
      content:
        "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
      author: "John F. Kennedy",
      tags: ["Change", "Future"],
      authorSlug: "john-f-kennedy",
      length: 105,
      dateAdded: "2020-12-17",
      dateModified: "2023-04-14",
    },
    {
      _id: "psDF8kzy2M",
      content:
        "You are not here merely to make a living. You are here in order to enable the world to live more amply, with greater vision, with a finer spirit of hope and achievement. You are here to enrich the world, and you impoverish yourself if you forget the errand.",
      author: "Woodrow Wilson",
      tags: ["Inspirational"],
      authorSlug: "woodrow-wilson",
      length: 257,
      dateAdded: "2019-11-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "cgBH5dPFK-jC",
      content:
        "I care not so much what I am to others as what I am to myself. I will be rich by myself, and not by borrowing.",
      author: "Michel de Montaigne",
      tags: ["Famous Quotes"],
      authorSlug: "michel-de-montaigne",
      length: 110,
      dateAdded: "2021-04-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "IvoOxxfBcYN",
      content: "Luck is what happens when preparation meets opportunity.",
      author: "Seneca the Younger",
      tags: ["Famous Quotes"],
      authorSlug: "seneca-the-younger",
      length: 56,
      dateAdded: "2021-01-30",
      dateModified: "2023-04-14",
    },
    {
      _id: "pR7t5Rox7GA2",
      content: "We make our own fortunes and we call them fate.",
      author: "Benjamin Disraeli",
      tags: ["Famous Quotes"],
      authorSlug: "benjamin-disraeli",
      length: 47,
      dateAdded: "2021-03-28",
      dateModified: "2023-04-14",
    },
    {
      _id: "GEqMoChoXn",
      content:
        "A wise man is superior to any insults which can be put upon him, and the best reply to unseemly behavior is patience and moderation.",
      author: "Molière",
      tags: ["Wisdom"],
      authorSlug: "moliere",
      length: 132,
      dateAdded: "2019-01-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "DNp5YdIcsG",
      content:
        "I never considered a difference of opinion in politics, in religion, in philosophy, as cause for withdrawing from a friend.",
      author: "Thomas Jefferson",
      tags: ["Friendship"],
      authorSlug: "thomas-jefferson",
      length: 123,
      dateAdded: "2021-01-11",
      dateModified: "2023-04-14",
    },
    {
      _id: "p2tRiR2FRe",
      content: "You always have two choices: your commitment versus your fear.",
      author: "Sammy Davis Jr.",
      tags: ["Wisdom"],
      authorSlug: "sammy-davis-jr",
      length: 62,
      dateAdded: "2019-07-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "nkftU-0YuUP6",
      content:
        "Courage is not the absence of fear, but simply moving on with dignity despite that fear.",
      author: "Pat Riley",
      tags: ["Famous Quotes"],
      authorSlug: "pat-riley",
      length: 88,
      dateAdded: "2021-04-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "d76RCKoNh69P",
      content: "Be your own hero, it's cheaper than a movie ticket.",
      author: "Doug Horton",
      tags: ["Famous Quotes"],
      authorSlug: "doug-horton",
      length: 51,
      dateAdded: "2019-02-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "ZsD4Hq1Z5",
      content:
        "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious.",
      author: "Stephen Hawking",
      tags: ["Inspirational"],
      authorSlug: "stephen-hawking",
      length: 142,
      dateAdded: "2019-03-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "Rx5_LAiVmhoP",
      content:
        "Do not scorn what you have received, nor envy the gains of others. He who envies others does not obtain peace of mind.",
      author: "The Buddha",
      tags: ["Wisdom"],
      authorSlug: "the-buddha",
      length: 118,
      dateAdded: "2021-01-20",
      dateModified: "2023-04-14",
    },
    {
      _id: "F8x4_uMBx-eO",
      content:
        "Let the future tell the truth and evaluate each one according to his work and accomplishments. The present is theirs; the future, for which I have really worked, is mine.",
      author: "Nikola Tesla",
      tags: ["Future", "Famous Quotes"],
      authorSlug: "nikola-tesla",
      length: 170,
      dateAdded: "2019-11-26",
      dateModified: "2023-04-14",
    },
    {
      _id: "qTGVTGcMFdZ",
      content: "Imagination rules the world.",
      author: "Napoleon",
      tags: ["Famous Quotes"],
      authorSlug: "napoleon",
      length: 28,
      dateAdded: "2020-02-07",
      dateModified: "2023-04-14",
    },
    {
      _id: "udQR137ixwNN",
      content: "A man is not old as long as he is seeking something.",
      author: "Edmond Rostand",
      tags: ["Famous Quotes"],
      authorSlug: "edmond-rostand",
      length: 52,
      dateAdded: "2021-03-08",
      dateModified: "2023-04-14",
    },
    {
      _id: "BK4faURIR8",
      content: "Be slow in choosing a friend, slower in changing.",
      author: "Benjamin Franklin",
      tags: ["Friendship"],
      authorSlug: "benjamin-franklin",
      length: 49,
      dateAdded: "2019-02-21",
      dateModified: "2023-04-14",
    },
    {
      _id: "_KiEvJQt0dRj",
      content: "Your big opportunity may be right where you are now.",
      author: "Napoleon Hill",
      tags: ["Famous Quotes"],
      authorSlug: "napoleon-hill",
      length: 52,
      dateAdded: "2020-12-19",
      dateModified: "2023-04-14",
    },
    {
      _id: "6dj60GUobqhK",
      content:
        "Think for yourselves and let others enjoy the privilege to do so too.",
      author: "Voltaire",
      tags: ["Famous Quotes"],
      authorSlug: "voltaire",
      length: 69,
      dateAdded: "2020-04-02",
      dateModified: "2023-04-14",
    },
    {
      _id: "sH3MhnCnnbWk",
      content:
        "Sometimes our fate resembles a fruit tree in winter. Who would think that those branches would turn green again and blossom, but we hope it, we know it.",
      author: "Johann Wolfgang von Goethe",
      tags: ["Famous Quotes"],
      authorSlug: "johann-wolfgang-von-goethe",
      length: 152,
      dateAdded: "2020-09-09",
      dateModified: "2023-04-14",
    },
    {
      _id: "hv83OL-O-fTP",
      content:
        "It is only when the mind and character slumber that the dress can be seen.",
      author: "Ralph Waldo Emerson",
      tags: ["Famous Quotes"],
      authorSlug: "ralph-waldo-emerson",
      length: 74,
      dateAdded: "2019-08-03",
      dateModified: "2023-04-14",
    },
    {
      _id: "jQHjwwHpLN",
      author: "Thomas Edison",
      content:
        "Results! Why, man, I have gotten a lot of results. I know several thousand things that won't work.",
      tags: ["Success", "Failure", "Perseverance"],
      authorSlug: "thomas-edison",
      length: 98,
      dateAdded: "2023-04-14",
      dateModified: "2023-04-14",
    },
    {
      _id: "JjBqM4t-sxsr",
      content:
        "Wise men talk because they have something to say; fools, because they have to say something.",
      author: "Plato",
      tags: ["Famous Quotes"],
      authorSlug: "plato",
      length: 92,
      dateAdded: "2019-11-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "Z9WzZIllCHeX",
      content:
        "An optimist is a person who sees a green light everywhere, while the pessimist sees only the red spotlight... The truly wise person is color-blind.",
      author: "Albert Schweitzer",
      tags: ["Famous Quotes"],
      authorSlug: "albert-schweitzer",
      length: 147,
      dateAdded: "2019-08-16",
      dateModified: "2023-04-14",
    },
    {
      _id: "QTf15XLSdB",
      content:
        "I think that we have a great opportunity to impart our wisdom and our knowledge and our experience to this younger generation. It may be different times, but experience transcends time, and wisdom transcends time.",
      author: "Victoria Osteen",
      tags: ["Wisdom"],
      authorSlug: "victoria-osteen",
      length: 213,
      dateAdded: "2021-01-11",
      dateModified: "2023-04-14",
    },
    {
      _id: "AEocdFfGOhyx",
      content: "What we see depends mainly on what we look for.",
      author: "John Lubbock",
      tags: ["Famous Quotes"],
      authorSlug: "john-lubbock",
      length: 47,
      dateAdded: "2020-01-27",
      dateModified: "2023-04-14",
    },
    {
      _id: "eDuDLZphbw9c",
      content: "The best preparation for tomorrow is doing your best today.",
      author: "H. Jackson Brown Jr.",
      tags: ["Famous Quotes"],
      authorSlug: "h-jackson-brown-jr",
      length: 59,
      dateAdded: "2020-01-15",
      dateModified: "2023-04-14",
    },
    {
      _id: "th7dUn_879",
      content:
        "I know that inner wisdom is more precious than wealth. The more you spend it, the more you gain.",
      author: "Oprah Winfrey",
      tags: ["Wisdom"],
      authorSlug: "oprah-winfrey",
      length: 96,
      dateAdded: "2019-07-23",
      dateModified: "2023-04-14",
    },
    {
      _id: "vvI7HzgTSh_",
      author: "The Buddha",
      content:
        "'As I am, so are these. As are these, so am I.' Drawing the parallel to yourself, neither kill nor get others to kill.",
      tags: ["Wisdom", "Virtue", "Honor"],
      authorSlug: "the-buddha",
      length: 118,
      dateAdded: "2023-03-30",
      dateModified: "2023-04-14",
    },
    {
      _id: "nr2GQYc-Hg",
      author: "Abraham Lincoln",
      content: "If I were two-faced, would I be wearing this one?",
      tags: ["Humorous"],
      authorSlug: "abraham-lincoln",
      length: 49,
      dateAdded: "2022-03-12",
      dateModified: "2023-04-14",
    },
    {
      _id: "X1jdRU0Azian",
      content: "Those who cannot learn from history are doomed to repeat it.",
      author: "George Santayana",
      tags: ["Wisdom"],
      authorSlug: "george-santayana",
      length: 60,
      dateAdded: "2019-01-14",
      dateModified: "2023-04-14",
    },
  ],
};
